#!/bin/bash
if  ( command -v wslpath &> /dev/null ) ; then
	#echo "Running on WSL"
	ONWSL=true
else	
	#echo "wsl not available "
	ONWSL=false
fi

if [[ "$3" = "" ]]; then
	SLICE=30
else
	SLICE=$3
fi

#echo "Slice time is $SLICE"

VARIANCE=5

LOWER=$[SLICE - $VARIANCE]
UPPER=$[SLICE + $VARIANCE]

#echo $LOWER
#echo $UPPER

#exit

#ONWSL=false

echo "# mpv EDL v0"
for (( i=1 ; i<=$2 ; i++ )); do
	while IFS=, read -r name length; do
		#echo "$name" "$length" >> length_records.txt
		if [[ -n "$length" ]] && [[ "$length" != "0" ]] && [[ ! "$length" == "N"* ]]; then 
			period=$(shuf -i $LOWER-$UPPER -n 1 )
			strt=$(rand -M $length -s $period )
			while true; do
			#echo "Length $length Start $strt Period $period"
				runtime=$(( $strt + $period ))
				#echo "Runtime $runtime"
				if [ "$length" -lt "$runtime" ]; then
					period=$[ "$period" - "1" ]
				else
					break
				fi
			done
			if ( $ONWSL ); then
				echo "$(wslpath -m "$name"),$strt,$period"
			else
				echo "$name,$strt,$period"
			fi
			#echo "$(wslpath -m "$name"),$strt,$period"
		else
			echo "No length for $name" 

		fi
	done < "$1"
done

