#!/bin/bash
TMPFILE=$(mktemp)
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
# set me
#FILES="$1"
#FILES=/mnt/d/edl/handmade/unix/*.edl

SCREEN=0
QUAD=1
		
for f in "$@"
do
	echo "$SRC/4lyum 1920 1920 $SCREEN $QUAD $f 50 " >> $TMPFILE
	QUAD=$((QUAD + 1 ))
	if [ $QUAD == 5 ] 
		then 
			QUAD=1	
			SCREEN=$((SCREEN + 1))
			if [ $SCREEN == 3 ] 
				then 
					SCREEN=0
					#echo "read -p Cont" >> $TMPFILE
			fi
	fi
	
done
# restore $IFS
IFS=$SAVEIFS

#shuf $TMPFILE -n 12
cat $TMPFILE

