#!/bin/bash
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
# set me
#FILES="$1"
#FILES=/mnt/d/edl/handmade/unix/*.edl

SCREEN=0
QUAD=1
		
for f in "$@"
do
	echo "/4lyum 1920 1080 $SCREEN $QUAD $f 50 &"
	QUAD=$((QUAD + 1 ))
	if [ $QUAD == 5 ] 
		then 
			QUAD=1	
			SCREEN=$((SCREEN + 1))
			if [ $SCREEN == 3 ] 
				then 
					SCREEN=0
			fi
	fi
	
done
# restore $IFS
IFS=$SAVEIFS
