#!/bin/bash
TMPFILE=$(mktemp)
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

THISPATH="$GRLSRC/$1"

if [ ! -d "$THISPATH" ] ; then
	echo "$THISPATH Not found"
	exit
fi

total=$(find "$THISPATH" -type f -name '*.mp*' | wc -l)

tenpercent=$(( total / 10 ))

decile=10

j=0

find "$THISPATH" -type f -name '*.mp*' -print0 | while IFS= read -r -d '' f; 
do
	#echo $f
	leng=$(ffprobe -v quiet  -of csv=p=0 -show_entries format=duration $f)
	sex=${leng%.*}
	[[ ! -z "$sex" ]] && echo "$f,$sex" >> $TMPFILE
	((j++))
	if [[ "$j" -eq "$tenpercent" ]]; then
	        j=0
		echo "$decile percent complete"
        	decile=$(( "$decile" + "10" ))
	fi
done
# restore $IFS
IFS=$SAVEIFS
cat $TMPFILE
cp $TMPFILE $EDLSRC/$1_sizes -v
