#!/bin/bash
TMPFILE=$(mktemp)
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

for d in ` find $GRLSRC/ -mindepth 1 -maxdepth 1 -type d `
do
	#echo $d
	if [[ ! $d == *".Trash"* ]]; then
		echo "$SRC/regenerate_length " "$(basename "$d")" >> $TMPFILE
	fi
done
# restore $IFS
IFS=$SAVEIFS
cat $TMPFILE
read -p "Press return to execute"
chmod +x $TMPFILE
bash -x $TMPFILE
