#!/bin/bash
TMPFILE=$(mktemp)
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

for f in $GRLSRC/$1/* `find  -type f -iname "*.m*"`
do
	#echo $f
	leng=$(ffprobe -v quiet  -of csv=p=0 -show_entries format=duration $f)
	sex=${leng%.*}
	[[ ! -z "$sex" ]] && echo "$f,$sex" >> $TMPFILE
done
# restore $IFS
IFS=$SAVEIFS
cat $TMPFILE
cp $TMPFILE $EDLSRC/$1_sizes -v
